### PR TITLE
Run simulations as kubernetes Jobs

### PR DESCRIPTION
**Pull request by hdoupe**
This PR makes it possible to run simulations or other tasks as [Kubernetes Jobs](https://kubernetes.io/docs/concepts/workloads/controllers/jobs-run-to-completion/) instead of submitting them to celery workers. The advantage of this approach is that Kubernetes takes care of scheduling the jobs, spinning up pods, adding compute resources if needed, and then cleaning up the resources afterwards. The disadvantage is that there may be some delays as pods are spun up, docker images are loaded (if they are not already loaded on or near the server), and that a new server may need to be spun up to run the job. However, this is OK as the overhead should only be 20-30 seconds at the most, and the tasks that need fast turn-around times like the ones for retrieving and validating inputs are still run as celery workers.

Sort of like Airflow, the code in this PR is split into a `client` package and an `executor` package. The `client` package has three main classes:
- `Publish`: configure model builds and deploys, pushing docker images, testing models.
- `Job`: create and delete Kubernetes Jobs.
- `Secret`: create, change, view, delete secrets. 

The `executor` package is the code that is actually running the tasks on the servers:
- `kubernetes`: executor that runs Kubernetes Jobs
- `celery`: executor that runs celery tasks.

So far, I've directly run simulations using this script:

```python
from cs_publish.client.job import Job

job = Job(
    project="cs-workers-dev",
    owner="PSLmodels",
    title="Tax-Cruncher",
    tag="test-job",
    job_kwargs={
        "adjustment": {"Policy": {}, "Tax Information": {}},
        "meta_param_dict": {"year": 2020},
    },
    quiet=False,
)

job.create()
```

Next, I need to update the flask webserver to so that it can submit jobs using the `Job` class. Once this is working, I plan to merge these changes into the main compute-studio repository, and this repo will be used for running CI/CD for models on C/S.

### CODE REVIEW

**Comment by hdoupe** [comment]
One of the really cool side-effects of using Kubernetes Jobs is that we no longer have to worry about the multiprocessing limits on celery workers. This way computationally intensive models can take advantage of larger servers by parallelizing their runs across the cores of a single server. 

cc @jdebacker @rickecon

**Comment by rickecon** [comment]
@hdoupe Yes. This is great. The spin up time pales in comparison to the 7-10x speedup that we get from parallelization in [OG-USA](https://github.com/PSLmodels/OG-USA). And if the parallelization can be expanded to a larger number of nodes, we might be able to get closer to 20x speedup. Very excited for this PR.

**Comment by hdoupe** [comment]
Thanks @rickecon. I'm excited for this batch of work, too: automatic updates to models + better scaling and lower compute costs. It will also open up the door for more infrastructure enhancements in the future.

**Comment by hdoupe** [comment]
I'm going to go ahead and merge #9 to begin the process of adding the code in this repository to the main C/S repository.

**Pull request merged**
