### PR TITLE
Update PSLmodels/Tax-Brain - 2020-10-13 09:03

### PR DESCRIPTION
**Pull request by hdoupe**

### CODE REVIEW

**Comment by hdoupe** [comment]
@andersonfrailey

**Comment by andersonfrailey** [comment]
Looks like `random_seed_from_subdict` function needs to be updated to handle parmtools style policy inputs instead of taxcalc style. Should be an easy fix. I'll use the same function that I used to fix the reports issue.

**Comment by hdoupe** [comment]
@andersonfrailey that sounds great.

**Comment by andersonfrailey** [comment]
PR opened [here](https://github.com/PSLmodels/Tax-Brain/pull/141).

**Comment by hdoupe** [comment]
@andersonfrailey Looks like another test failure related to pandoc.

**Comment by andersonfrailey** [comment]
@hdoupe yeah looks like PDFLatex needs to be installed. I'll add it to the install instructions.

**Comment by andersonfrailey** [comment]
@hdoupe just updated the environment and install scripts.

**Comment by hdoupe** [comment]
Thanks @andersonfrailey. Really appreciate you working through the testing issues!

**Comment by hdoupe** [comment]
@andersonfrailey looks like there was an error collecting the tests.... :thinking: 

Screenshot from 2020-12-10 11-45-05


https://github.com/compute-tooling/compute-studio-publish/runs/1531956868#step:9:23

**Comment by andersonfrailey** [comment]
@hdoupe, Well that's new. I'll look into it. I'm going to take it as a good sign that we're getting new types of errors though

**Pull request merged**
