### PR TITLE
Update Peter-Metz/state-taxdata - 2020-07-23 12:53

### PR DESCRIPTION
**Pull request by hdoupe**
cc @peter-metz

### CODE REVIEW

**Comment by hdoupe** [comment]
@peter-metz is there a way to run the tests without having the actual PUF file? The secrets for reading the PUF are available when the app is run but not in testing. I'd have to think through how to do this securely in a public build forum.

**Comment by Peter-Metz** [comment]
@hdoupe at the moment all of the tests rely on the PUF. I could certainly consider changing tests to run with a fuzzed PUF or the CPS. That would also let us use Travis in the state_taxdata repo

**Comment by hdoupe** [comment]
@peter-metz actually, I have a couple ideas for how to do this. Let me try those real quick and then I'll try the build again..

**Comment by hdoupe** [comment]
@Peter-Metz The secrets problem is resolved now. The error message is a little hidden in the CI output, but here's the traceback:

```
    def retrieve_puf(aws_access_key_id, aws_secret_access_key):
        """
        Function for retrieving the PUF from the OSPC S3 bucket
        """
        has_credentials = aws_access_key_id and aws_secret_access_key
        if has_credentials and boto3 is not None:
            client = boto3.client(
                "s3",
                aws_access_key_id=aws_access_key_id,
                aws_secret_access_key=aws_secret_access_key,
            )
            obj = client.get_object(Bucket="ospc-data-files", Key="puf.csv.gz")
            gz = gzip.GzipFile(fileobj=obj["Body"])
>           puf_df = pd.read_csv(gz)
E           NameError: name 'pd' is not defined
```

**Comment by Peter-Metz** [comment]
@hdoupe whoops, just fixed that

**Comment by hdoupe** [comment]
@Peter-Metz Getting this error now (here's a snippet, full traceback is in the log):

```
state_taxdata/state_taxdata/prepdata.py:200: in filter_puf
    puf_2017 = puf_indicators()
state_taxdata/state_taxdata/prepdata.py:166: in puf_indicators
    puf_2017 = puf_to_2017()
state_taxdata/state_taxdata/prepdata.py:143: in puf_to_2017
    if self.puf_df == None:
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

self =         elderly_dependents  age_head  age_spouse  ...  g20500  pencon_p  pencon_s
0                    False     False...    False
248590               False     False       False  ...   False     False     False

[248591 rows x 89 columns]

    def __nonzero__(self):
        raise ValueError(
>           f"The truth value of a {type(self).__name__} is ambiguous. "
            "Use a.empty, a.bool(), a.item(), a.any() or a.all()."
        )
E       ValueError: The truth value of a DataFrame is ambiguous. Use a.empty, a.bool(), a.item(), a.any() or a.all().

/opt/conda/lib/python3.7/site-packages/pandas/core/generic.py:1479: ValueError
=========================== short test summary info ============================
FAILED test_functions.py::TestFunctions1::test_run_model - ValueError: The tr...
```

**Comment by Peter-Metz** [comment]
@hdoupe strange...the tests are still passing locally. I changed a bit of syntax that was hopefully the culprit

**Comment by hdoupe** [comment]
Thanks @Peter-Metz! Hopefully this fixes the problem.

**Pull request merged**
